.gitignore
frontend/.gitignore
frontend/package-lock.json
frontend/package.json
frontend/src/App.jsx
frontend/src/Pages/LoginPage/LoginPage.jsx
frontend/src/components/Context/Context.jsx
frontend/src/components/Login/Login.jsx
frontend/src/components/Navbar/Navbar.jsx
readme.md
server/app.py

- Add login page with form (not submitting to DB yet), 
- update dependencies on main.jsx (material UI, react-router-dom)
- add folder structure for frontend components, services, router. 
- Add Navbar component (unused), add boilerplate to main.jsx. 
- removed login jinja template

P001 login - Page 

---

frontend/.env
frontend/.gitignore
frontend/src/Pages/LoginPage/LoginPage.jsx
frontend/src/services/authentication.js
frontend/src/services/users.js

- Refactor of login page state variables
- Form functionality fixed to prevent default form behaviour
- added service files for authentication and users

P001 login - fix login form, add service files

---

frontend/src/App.jsx
frontend/src/Pages/SignUpPage/SignUpPage.jsx

Crated Sign up form with firstname, lastname, email address, password, confirm password and shelter

Sign up page

---

frontend/src/services/animals.js

- removed Duplicate code on animal.js breaking login page

bugfix animal.js: removed duplicated lines

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.jsx
frontend/src/Pages/AnimalAdvertPage/AnimalAdvertPage.jsx
frontend/src/services/animals.js
server/app.py

- Fixed backend data issue so that data is being passed from backend to frontend React components 
- Needed to add animal id from params so backend route could recognise which animal is being requested
-

fixed animal advert component

---

frontend/src/Pages/Animals/animals.jsx
frontend/src/components/AnimalCard/animalcard.jsx

Updated styling on animal cards and now linking to Marya's changes to individual adverts

updated animal card changes

---

frontend/src/App.jsx

just to fix 1 line on app.jsx, duplicated import of allanimals

bugfix app.jsx: remove additional import of allanimals

---

server/db/database_connection.py
server/db/seed.py

Made better use of the .env file - this will help with hosting this application externally. 
The seed file and database connection file needed to use the Python dotenv library.

Minor improvement to database connection

---

frontend/package-lock.json
frontend/package.json
frontend/src/Pages/SignUpPage/SignUpPage.jsx
frontend/tests/Pages/SignUpPage.test.jsx
frontend/vite.config.js

Added new Password validation for Sign up Page

Sign up password vaidation

---

server/app.py

- change to login code to ensure user is being captured

bigfix login: change code to ensure user is being captured before check

---

frontend/src/Pages/SignUpPage/SignUpPage.jsx
server/app.py

- Return signup when user is created

bugfix signup: return token with signup

---

frontend/src/Pages/Animals/animals.jsx

minor change to styling for animal card component

amended the layout for max 3 animals

---

frontend/src/services/animals.js
server/app.py

Added backend functionality in Flask to edit an existing animal, atm does not check for shelter_id in token

Edit animal backend]

---

server/app.py
server/db/seed.py

very minor changes - see file compares below.

simple change to app.py and seed.py

---

frontend/package-lock.json
frontend/package.json
frontend/src/Pages/SignUpPage/SignUpPage.jsx
frontend/tests/Pages/SignUpPage.test.jsx
frontend/vite.config.js

tests-for-sign-up-page

---

frontend/src/Pages/CreateAdvertPage/CreateAdvertPage.jsx

Create animal form dropdowns

---

frontend/src/Pages/LoginPage/LoginPage.jsx

perf password: obfuscate password at login

---

server/app.py
server/db/seed.py

Data : Seed : Added a new status field to the schema

New Status Field for the Animal records

---

frontend/src/Pages/AnimalAdvertPage/AnimalAdvertPage.jsx
frontend/src/Pages/CreateAdvertPage/CreateAdvertPage.jsx
frontend/src/services/animals.js
server/app.py
server/db/models/Animal.py
server/templates/upload.html

Reverts rokesby/animal-adoption#72

Revert "Add images to create advert and animal advert"

---

frontend/src/App.css
frontend/src/Pages/Animals/animals.jsx
frontend/src/Pages/LoginPage/LoginPage.jsx
frontend/src/Pages/SignUpPage/SignUpPage.jsx
frontend/src/components/AnimalCard/animalcard.jsx
frontend/src/components/Navbar/Navbar.jsx
frontend/src/index.css
frontend/src/services/animals.js

P 020 styling
